[[redirects]]
  from = "/api/*"
  to = "http://139.190.96.203:8092/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "http://139.190.96.203:8092/health"
  status = 200

[[redirects]]
from = "/uploads/*"
to = "http://139.190.96.203:8092/uploads/:splat"
status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
